image: diceengineering/hydro:latest

build:
  before_script:
    # check this out: https://docs.gitlab.com/ee/ci/ssh_keys/
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$GITLAB_CI_SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh
    - chmod 700 ~/.ssh/id_rsa
    - ssh-add
    # also add the known hosts so we don't have to accept when connecting to the host
    - echo "$GITLAB_CI_SSH_KNOWN_HOST" | tr -d '\r' > ~/.ssh/known_hosts
  script:
    - rm -rf build
    - mkdir build
    - cd build
    - cmake .. -DMESHOUI_USE_MMG=ON -DUSE_VTK=ON
    - make all test -j4

test:
  script:
    make test
